### ISSUE TITLE
Luxon unable to parse empty policy.json file

### ISSUE THREAD

**Issue by HieronymusCrouse** [TachyonicProject/luxon#105]
In order to replicate, simply process a view that returns a `render_template` while the policy.json file is empty:

`Jun 04 15:59:12 Application luxon.core.handlers.wsgi.application[25479] <WARNING>: luxon.exceptions.JSONDecodeError: JSON Decode; Expecting value: line 1 column 1 (char 0) (REMOTE-HOST: 127.0.0.1) (REQUEST-ID: 25479-1ba17045)
`

**Comment by cfrademan** [comment]
This is expected behaviour. Valid json is bare minimim of root object such as {} or [].

**Comment by Vuader** [comment]
@HieronymusCrouse as @cfrademan mentioned, this is functioning as designed. So, instead of allowing users to use blank/invalid policy.json files, we only updated the Exception description to indicate that the JSONDecodeError happened on the policy.json file. This should come in useful when people are unable to view the Traceback in the Debug Logs, where one would have at least been able to see that the luxon.helpers.policy file was the origin of the exception. This was done in commit 106/108
